spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123

  jpa:
    show-sql: false
  flyway:
    validate-migration-naming: on
    validate-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /api


